#
# Copyright (c) 2006-2024, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0
#
# Change Logs:
# Date           Author       Notes
# 2024-07-19     supperthomas the first version
#
name:  action_runner

# Controls when the action will run. Triggers 'scons --dist' to build the dist
on:
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      bsp_options:
        description: 'Which bsp path Would you want dist in bsp?like stm32/stm32f103-blue-pill '
        required: false
        type: string
        default: 'stm32/stm32f103-blue-pill'
      bsp_tool_chain:
        description: 'Choice tool_chain'
        required: false
        default: 'KEIL'
        type: choice
        options:
          - "KEIL"
          - "IAR"
      bsp_config:
        description: 'Type a config you want mannual test in .config, like: CONFIG_RT_USING_DEBUG=y,CONFIG_RT_DEBUGING_COLOR=y,CONFIG_RT_DEBUGING_CONTEXT=y'
        required: false
        type: string
        default: 'CONFIG_RT_USING_DEBUG=y,CONFIG_RT_DEBUGING_COLOR=y,CONFIG_RT_DEBUGING_CONTEXT=y'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    name: ${{ github.event.inputs.bsp_options }}
    steps:
      - uses: actions/checkout@v3
      - name: Bsp Scons Compile
        if: ${{ success() }}
        shell: bash
        env:
          RTT_BSP: ${{ github.event.inputs.bsp_options }}
          RTT_TOOL_CHAIN: ${{ github.event.inputs.bsp_tool_chain}}
        run: |   
          ls
          echo $RTT_BSP
          #cd bsp/$RTT_BSP
          #cd bsp/stm32/stm32f103-blue-pill
          #scons --target=mdk5
          #UV4.exe -b project.uvprojx -q -j0 -t rt-thread -o action_runner.log
          #ls
          #sleep 10
          #cat action_runner.log
          for subfolder in bsp/stm32/*/
          do
              if [ -d "$subfolder" ]; then
                  cd "$subfolder"
                  echo "Executing in $subfolder"
                  echo
                  cd -
              fi
          done
          
